language: node_js
node_js:
  # we can't use latest because 11.11 breaks jest's env variable mock
  - "11.10.1"

cache: npm

before_install:
  - cd dev-portal
  # install everything in dev portal
  - npm install
  - cd ..
  # lambda function test dependencies are currently installed at the top-level
  - npm install --only=dev